- name: variables in ansible
  hosts: viswa
  # This is Play level variables, map
  vars_files:
  - variables.yaml
  - variables.yaml
  tasks:
  - name: print hello world
    ansible.builtin.debug:
      msg: "Hello, I am learning Ansible"
  - name: print variables
    ansible.builtin.debug:
      msg: "Hello, I am learning {{COURSE}}, Trainer is {{TRAINER}}, Duration is {{DURATION}}, and {{LOCATION}}"